/* tslint:disable */
/* eslint-disable */
/**
 * Ms Feed API
 * Ms Feed API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ReelRequest } from '../model';
/**
 * MsNotificationKafkaResourceApi - axios parameter creator
 * @export
 */
export const MsNotificationKafkaResourceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ReelRequest} reelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendReelDirectly: async (reelRequest: ReelRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reelRequest' is not null or undefined
            assertParamExists('sendReelDirectly', 'reelRequest', reelRequest)
            const localVarPath = `/api/kafka-test/send-reel-direct`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reelRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MsNotificationKafkaResourceApi - functional programming interface
 * @export
 */
export const MsNotificationKafkaResourceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MsNotificationKafkaResourceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ReelRequest} reelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendReelDirectly(reelRequest: ReelRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendReelDirectly(reelRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MsNotificationKafkaResourceApi.sendReelDirectly']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MsNotificationKafkaResourceApi - factory interface
 * @export
 */
export const MsNotificationKafkaResourceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MsNotificationKafkaResourceApiFp(configuration)
    return {
        /**
         * 
         * @param {ReelRequest} reelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendReelDirectly(reelRequest: ReelRequest, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.sendReelDirectly(reelRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MsNotificationKafkaResourceApi - object-oriented interface
 * @export
 * @class MsNotificationKafkaResourceApi
 * @extends {BaseAPI}
 */
export class MsNotificationKafkaResourceApi extends BaseAPI {
    /**
     * 
     * @param {ReelRequest} reelRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MsNotificationKafkaResourceApi
     */
    public sendReelDirectly(reelRequest: ReelRequest, options?: RawAxiosRequestConfig) {
        return MsNotificationKafkaResourceApiFp(this.configuration).sendReelDirectly(reelRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

