/* tslint:disable */
/* eslint-disable */
/**
 * Ms Feed API
 * Ms Feed API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommentDTO } from './comment-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { RedisUserDTO } from './redis-user-dto';

/**
 * 
 * @export
 * @interface CommentWithRedisUserDTO
 */
export interface CommentWithRedisUserDTO {
    /**
     * 
     * @type {CommentDTO}
     * @memberof CommentWithRedisUserDTO
     */
    'commentDTO'?: CommentDTO;
    /**
     * 
     * @type {RedisUserDTO}
     * @memberof CommentWithRedisUserDTO
     */
    'redisUserDTO'?: RedisUserDTO;
}

