/* tslint:disable */
/* eslint-disable */
/**
 * Ms Feed API
 * Ms Feed API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommentDTO
 */
export interface CommentDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    'parentType': string;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    'parentId': string;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    'createdAt': string;
}

