/* tslint:disable */
/* eslint-disable */
/**
 * Ms Reel API
 * Ms Reel API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FeedItemDTO
 */
export interface FeedItemDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedItemDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FeedItemDTO
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof FeedItemDTO
     */
    'reelId': string;
    /**
     * 
     * @type {string}
     * @memberof FeedItemDTO
     */
    'timestamp': string;
}

