/* tslint:disable */
/* eslint-disable */
/**
 * Ms Commentlike API
 * Ms Commentlike API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FeedItemDTO } from './feed-item-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { RedisUserDTO } from './redis-user-dto';

/**
 * 
 * @export
 * @interface FeedWithOtherDTO
 */
export interface FeedWithOtherDTO {
    /**
     * 
     * @type {FeedItemDTO}
     * @memberof FeedWithOtherDTO
     */
    'feedItem'?: FeedItemDTO;
    /**
     * 
     * @type {RedisUserDTO}
     * @memberof FeedWithOtherDTO
     */
    'redisUserDTO'?: RedisUserDTO;
    /**
     * 
     * @type {number}
     * @memberof FeedWithOtherDTO
     */
    'likeCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedWithOtherDTO
     */
    'commentCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedWithOtherDTO
     */
    'shareCount'?: number;
}

