/* tslint:disable */
/* eslint-disable */
/**
 * Ms Commentlike API
 * Ms Commentlike API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeycloakUserDTO
 */
export interface KeycloakUserDTO {
    /**
     * 
     * @type {string}
     * @memberof KeycloakUserDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof KeycloakUserDTO
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof KeycloakUserDTO
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof KeycloakUserDTO
     */
    'realmId': string;
    /**
     * 
     * @type {string}
     * @memberof KeycloakUserDTO
     */
    'userId': string;
}

