/* tslint:disable */
/* eslint-disable */
/**
 * Ms Feed API
 * Ms Feed API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LikeDTO } from './like-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { RedisUserDTO } from './redis-user-dto';

/**
 * 
 * @export
 * @interface LikeWithRedisUserDTO
 */
export interface LikeWithRedisUserDTO {
    /**
     * 
     * @type {RedisUserDTO}
     * @memberof LikeWithRedisUserDTO
     */
    'redisUserDTO'?: RedisUserDTO;
    /**
     * 
     * @type {LikeDTO}
     * @memberof LikeWithRedisUserDTO
     */
    'likeDTO'?: LikeDTO;
}

