/* tslint:disable */
/* eslint-disable */
/**
 * Ms Commentlike API
 * Ms Commentlike API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationDTO
 */
export interface NotificationDTO {
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'recipientId': string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDTO
     */
    'isRead': boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'createdAt': string;
}

