/* tslint:disable */
/* eslint-disable */
/**
 * Ms Feed API
 * Ms Feed API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RedisUserDTO
 */
export interface RedisUserDTO {
    /**
     * 
     * @type {string}
     * @memberof RedisUserDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedisUserDTO
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedisUserDTO
     */
    'userAvatar'?: string;
}

