/* tslint:disable */
/* eslint-disable */
/**
 * Ms Reel API
 * Ms Reel API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReelDTO
 */
export interface ReelDTO {
    /**
     * 
     * @type {string}
     * @memberof ReelDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ReelDTO
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof ReelDTO
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ReelDTO
     */
    'videoUrl': string;
    /**
     * 
     * @type {string}
     * @memberof ReelDTO
     */
    'createdAt': string;
}

