/* tslint:disable */
/* eslint-disable */
/**
 * Ms Feed API
 * Ms Feed API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReelRequest
 */
export interface ReelRequest {
    /**
     * 
     * @type {string}
     * @memberof ReelRequest
     */
    'eventName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReelRequest
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReelRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReelRequest
     */
    'videoUrl'?: string;
}

